- hosts: terraform-ansible
  become: yes
  tasks:
  - name: Instalando o python3, virtualenv
    apt:
      pkg:
      - python3
      - python3-venv
      - virtualenv
      update_cache: yes

  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/guilhermeonrails/clientes-leo-api.git
      dest: /home/ubuntu/tcc
      version: master
      force: yes

  - name: Criar ambiente virtual
    shell: python3 -m venv /home/ubuntu/tcc/venv

  - name: Instalando dependências com pip
    # pip:
    #   virtualenv: /home/ubuntu/tcc/venv
    #   requirements: /home/ubuntu/tcc/requirements.txt
    shell: |
      . /home/ubuntu/tcc/venv/bin/activate
      pip install setuptools
      pip install -r /home/ubuntu/tcc/requirements.txt

  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

  - name: configurando o banco de dados
    shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py migrate'
    
  - name: carregando os dados iniciais
    shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py loaddata clientes.json'
  
  - name: inciando o servidor
    shell: '. /home/ubuntu/tcc/venv/bin/activate; nohup python /home/ubuntu/tcc/manage.py runserver 0.0.0.0:8000 &'

